language: cpp
os:
  - linux
  - osx
  - windows
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./bootstrap-linux.bash ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./bootstrap-macos.bash ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && bootstrap-windows.bat' ; fi
  - "bootstrap/bin/forge variant=release prefix=release/forge install"
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -zcvf ${TRAVIS_BUILD_DIR}/forge-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz forge/bin/* forge/lua/** ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -zcvf ${TRAVIS_BUILD_DIR}/forge-macos-${TRAVIS_TAG}.tar.gz forge/bin/* forge/lua/** ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then tar -zcvf ${TRAVIS_BUILD_DIR}/forge-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz forge/bin/* forge/lua/** ; fi
  - cd ${TRAVIS_BUILD_DIR}
deploy:
  provider: releases
  api_key:
    secure: BsX4oaoAHVy8rPsV/CICs1l9hk+3OXCXfXxoTW2Jw+uKGUVLI51t0MGyLhOwjKsYpu6HZb4jw3gs+uiFDVke2BRjFqEeOLC6J0/zc4j2Ui0c8tTl2dj1gI2JiKXVtsCPw6bwi7oceR1xEBS29Slg6sG9XjJuc8hFyV93xcasylhknPd2GP/QvGuprQOvIlsNxnCycUuMX4kts76r0gk7kTuI1makSwxJsVHr8e4alnZmIxxYxkr1ot/2D7nI0u/nS8vrky7LbnFlYUTZLt13r5J2eXvHNBZpX1IAj4j+hO/LYjDFOTtLo2Nx5OBe3yNVhT2q/Y4a9c0MNZn8norZvOtBjytNmiJWSXlZ0jA7XTJ/y7M1rSaDnIkanepWal9Mg5dw+YD4TVYO0ARf0GdZpNi809kRC1zraLigCXHwAdZxEbQgXTVwb6iR1R3HlZ5+BC/gNbRBjsuwf0g24w5M8bUTqkpQO3Iwuet3H+LUa3K5jAL6THZEYeQJgKBLmOkt9gjJBpubuqanJukxID5hl0JbwUIt1dPCdQAb1hTvRtse2TVV8whAHJ0BFVh3XQbiuZZBHICPLu8EMze5PQjOKl4wzKWCKLzmTvKk8gNYMtQYke8r9Ith2SDbFkkEshmf5FPxYs1aToXuB0jTsStSvwNTl9XhpPS3pasXW9Cz3b8=
  name: ${TRAVIS_TAG}
  file_glob: true
  file: forge-*-${TRAVIS_TAG}.*
  skip_cleanup: true
  prerelease: true
  draft: true
  on:
    repo: cwbaker/forge
    tags: true
