# Dependencies
# highlighter: pygments
markdown: kramdown

remote_theme: cwbaker/doc

kramdown:
  parse_block_html: true

# Permalinks
permalink: pretty

# Setup
title: forge
tagline: 'Lua-scriptable, file-based build tool'
description: 'Lua-scriptable, file-based build tool'
url: https://cwbaker.github.io
baseurl: 
author:
  name: 'Charles Baker'

# Custom vars
github_project: cwbaker/forge
downloads: https://github.com/cwbaker/forge/releases
version: 0.5

plugins:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-remote-theme
- jekyll-sitemap
- jemoji
