name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then bash ./bootstrap-linux.bash ; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then bash ./bootstrap-macos.bash ; fi
        if [[ "$RUNNER_OS" == "Windows" ]]; then ./bootstrap-windows.bat ; fi
        bootstrap/bin/forge
        debug/bin/forge variant=release prefix=forge install
      shell: bash
    - name: Test
      run: |
        release/bin/forge_test
      shell: bash
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: forge-${{ runner.os }}
        path: forge/**
