name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then bash ./bootstrap-linux.bash ; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then bash ./bootstrap-macos.bash ; fi
        if [[ "$RUNNER_OS" == "Windows" ]]; then ./bootstrap-windows.bat ; fi
        bootstrap/bin/forge variant=release
      shell: bash
    - name: Test
      run: |
        release/bin/forge_test
      shell: bash
