name: Create Release

on: 
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Collect Release Notes
      id: release_notes
      run: |
        last_release_commit=`git log -n1 --pretty=format:%H -- version.txt`
        commits=`git rev-list --count $last_release_commit..HEAD`
        version=`cat version.txt`.$commits
        git log --pretty=format:"- %s" $last_release_commit..HEAD >release_notes.txt
        echo "::set-output name=version::${version}"
      shell: bash
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.release_notes.outputs.version }}
        commitish: ${{ github.ref }}
        release_name: v${{ steps.release_notes.outputs.version }}
        body_path: ./release_notes.txt
        draft: true
        prerelease: true
